name: learntogther
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.10.0
  file_picker: ^10.2.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  fl_chart: ^0.71.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.1
  webview_flutter_wkwebview: ^3.23.0
  youtube_player_flutter: ^9.1.2
  youtube_player_iframe: ^5.2.2
  better_player: ^0.0.84
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-variant files and
  # display appropriate resolution-variant.
  # For details regarding adding assets from package dependencies,
  # see https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package